type FixedLengthArray<T, L extends number> = [T, ...T[]] & { length: L };

export const donors: FixedLengthArray<string, 73> = [
  'Dr. Tuen',
  'zomg#3195',
  'WhaiFuji',
  'mstrixie29',
  'Zxvro',
  'stephanigilliam',
  'kevlar_kid',
  'PretentiousLuck',
  'Szute',
  'EarwigHoneyHarvest#7183',
  'lainsan',
  'lewisc5',
  'DhrMekmek',
  'CW_Mikey',
  'Token Time',
  'Tigger',
  'Pete Tycoon',
  'Jofnan',
  'Zulima',
  'Mapaliciousness#3816',
  'melody#8113',
  'coffeepotlove',
  'Bokonon',
  'dman278',
  'eggfarmer2000',
  'FancyNewspaper',
  'CannonFodder',
  'KCCKirby#5225',
  'realtebo',
  'bombbomb345',
  'E* S*',
  'cynthia1960#9760',
  'JulesWinnfeild#0001',
  'illyana',
  'stratocastor',
  'superchlorine',
  'Thumblesspotato',
  'Andalite',
  'scorpnicole',
  'Toki',
  'DelaqueESN',
  'MightyMatt',
  'A* Z*',
  'Vijay',
  'Greggen',
  'grey#7865',
  '420gold#2928',
  'laura',
  'forty2#9911',
  'sugebishop#1356',
  'kc000034008',
  'jikerwa#1738',
  'DubstepCrushedMyEggs',
  'FredNet',
  'BelowAverage#7013',
  'Baumer8993#1788',
  'C* C*',
  'STAAAAAR',
  'HeftyHobbit',
  'blacketj',
  'K9Confetti',
  'RAIYC',
  'echo',
  'calvin1719',
  'Winter_Wiz4rd',
  'SoftAllan#5785',
  'Professor',
  'lazydesert#2563',
  'BobSki778',
  'benkyrie',
  'Soveliss',
  'NoxiousNinja#1968',
  'W1Z4RD#8721',
];
