type FixedLengthArray<T, L extends number> = [T, ...T[]] & { length: L };

export const donors: FixedLengthArray<string, 48> = [
  'Dr. Tuen',
  'zomg#3195',
  'WhaiFuji',
  'mstrixie29',
  'PretentiousLuck',
  'Szute',
  'lewisc5',
  'DhrMekmek',
  'CW_Mikey',
  'Token Time',
  'Tigger',
  'Pete Tycoon',
  'Zulima',
  'Mapaliciousness#3816',
  'melody#8113',
  'stephanigilliam',
  'coffeepotlove',
  'kevlar_kid',
  'Bokonon',
  'dman278',
  'FancyNewspaper',
  'KCCKirby#5225',
  'realtebo',
  'bombbomb345',
  'E* S*',
  'cynthia1960#9760',
  'JulesWinnfeild#0001',
  'illyana',
  'DelaqueESN',
  'MightyMatt',
  'Vijay',
  'Greggen',
  'grey#7865',
  '420gold#2928',
  'laura',
  'forty2#9911',
  'sugebishop#1356',
  'blacketj',
  'K9Confetti',
  'RAIYC',
  'SoftAllan#5785',
  'Professor',
  'lazydesert#2563',
  'BobSki778',
  'benkyrie',
  'Soveliss',
  'calvin1719',
  'W1Z4RD#8721',
];
